"""add server_default to project.updated_at

Revision ID: 0ed3d2214640
Revises: 3be2ec4bd17d
Create Date: 2026-07-23 01:13:27.101846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed3d2214640'
down_revision: Union[str, Sequence[str], None] = '3be2ec4bd17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column('project', 'updated_at',
        server_default=sa.text('now()'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
