"""add server_default to project.updated_at

Revision ID: 3be2ec4bd17d
Revises: bdb7e677eafc
Create Date: 2026-07-23 01:11:02.111050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be2ec4bd17d'
down_revision: Union[str, Sequence[str], None] = 'bdb7e677eafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
