"""create new index

Revision ID: 5d9fafbdc2c5
Revises: 3c00822c36b4
Create Date: 2026-08-09 01:52:59.599482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9fafbdc2c5'
down_revision: Union[str, Sequence[str], None] = '3c00822c36b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_name_task_args_hash'), table_name='celery_task_execution')
    op.drop_index(op.f('ix_task_execution_celery_task_id'), table_name='celery_task_execution')
    op.create_index('ix_task_execution_celery_task_id', 'celery_task_execution', ['celery_task_id'], unique=False)
    op.create_index('ix_task_name_task_args_hash_celery_task_id', 'celery_task_execution', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_task_args_hash_celery_task_id', table_name='celery_task_execution')
    op.drop_index('ix_task_execution_celery_task_id', table_name='celery_task_execution')
    op.create_index(op.f('ix_task_execution_celery_task_id'), 'celery_task_execution', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_task_name_task_args_hash'), 'celery_task_execution', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###
